[package]
name = "raptor-bot"
version = "0.1.0"
authors = ["mute1997 <mute1008@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
lazy_static = "1.3.0"
reqwest = "0.9.14"
serde = "1.0.90"
serde_derive = "1.0.90"
